In [2]:
# 1. 188
# 2. -180
# 3. 36
# 7. 65
# 8. 408
# 9. -288
# 13. - 156
# 14. 208
# 15. -288

In [3]:
# №1 Вычисления с матрицами

In [34]:
import numpy as np
A = np.array([
    [1, 2, 4],
    [7, 5, -2],
    [-2, 1, 3]
])

B = np.array([
    [-1, 0, 3],
    [2, -6, 1],
    [-7, 1, 5]
])

C = np.array([
    [-2, 3],
    [4, 0],
    [7, -1]
])

result_sum = A + B

print("A + B:")
print(result_sum)

result_subtraction = B - A
print("B - A:")
print(result_subtraction)

result_mult_AC = A @ C 
print("A * C:")
print (result_mult_AC)

result_mult_ABC = A @ B @ C 
print("A * B * C:")
print(result_mult_ABC)

A + B:
[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]
B - A:
[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]
A * C:
[[34 -1]
 [-8 23]
 [29 -9]]
A * B * C:
[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [35]:
# №2 Вычисления с матрицами

In [36]:
import numpy as np
A2 = np.array([
    [0, 3, 4],
    [-7, 1, -2],
    [2, -1, 3]
])

B2 = np.array([
    [1, 2, 4],
    [7, 0, -2],
    [-3, -2, 5]
])

C2 = np.array([
    [-3, 2],
    [0, 4],
    [-1, 7]
])

result_sum2 = A2 + B2

print("A2 + B2:")
print(result_sum2)

result_subtraction2 = B2 - A2
print("B2 - A2:")
print(result_subtraction2)

result_mult_AC2 = A2 @ C2 
print("A2 * C2:")
print (result_mult_AC2)

result_mult_ABC2 = A2 @ B2 @ C2 
print("A2 * B2 * C2:")
print(result_mult_ABC2)

A2 + B2:
[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]
B2 - A2:
[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]
A2 * C2:
[[ -4  40]
 [ 23 -24]
 [ -9  21]]
A2 * B2 * C2:
[[ -41   84]
 [  22 -308]
 [  17  139]]


In [37]:
# №3 Вычисления с матрицами

In [38]:
import numpy as np
A3 = np.array([
    [5, 2, 9],
    [7, 0, -2],
    [-2, 1, 6]
])

B3 = np.array([
    [1, -2, 1],
    [7, 5, -2],
    [-2, 8, 3]
])

C3 = np.array([
    [-2, 3],
    [4, 5],
    [0, -1]
])

result_sum3 = A3 + B3

print("A3 + B3:")
print(result_sum3)

result_subtraction3 = B3 - A3
print("B3 - A3:")
print(result_subtraction3)

result_mult_AC3 = A3 @ C3 
print("A3 * C3:")
print (result_mult_AC3)

result_mult_ABC3 = A3 @ B3 @ C3 
print("A3 * B3 * C3:")
print(result_mult_ABC3)

A3 + B3:
[[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]
B3 - A3:
[[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]
A3 * C3:
[[ -2  16]
 [-14  23]
 [  8  -7]]
A3 * B3 * C3:
[[ 286  335]
 [-142 -118]
 [ 242  250]]


In [39]:
# №4 Вычисления с матрицами

In [40]:
import numpy as np
A4 = np.array([
    [1, -2, 8],
    [7, 5, -2],
    [-2, 3, 0]
])

B4 = np.array([
    [0, 2, 4],
    [1, -3, -2],
    [-2, 1, 3]
])

C4 = np.array([
    [0, 3],
    [5, -4],
    [7, -1]
])

result_sum4 = A4 + B4

print("A4 + B4:")
print(result_sum4)

result_subtraction4 = B4 - A4
print("B4 - A4:")
print(result_subtraction4)

result_mult_AC4 = A4 @ C4 
print("A4 * C4:")
print (result_mult_AC4)

result_mult_ABC4 = A4 @ B4 @ C4 
print("A4 * B4 * C4:")
print(result_mult_ABC4)

A4 + B4:
[[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]
B4 - A4:
[[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]
A4 * C4:
[[ 46   3]
 [ 11   3]
 [ 15 -18]]
A4 * B4 * C4:
[[ 304 -150]
 [  69   27]
 [-163   75]]


In [41]:
# №5 Вычисления с матрицами

In [42]:
import numpy as np
A5 = np.array([
    [9, 2, 4],
    [7, 5, -5],
    [6, -2, 3]
])

B5 = np.array([
    [8, 2, 4],
    [0, 1, -3],
    [-2, 1, 6]
])

C5 = np.array([
    [-2, 0],
    [4, 8],
    [1, -1]
])

result_sum5 = A5 + B5

print("A5 + B5:")
print(result_sum5)

result_subtraction5 = B5 - A5
print("B5 - A5:")
print(result_subtraction5)

result_mult_AC5 = A5 @ C5 
print("A5 * C5:")
print (result_mult_AC5)

result_mult_ABC5 = A5 @ B5 @ C5 
print("A5 * B5 * C5:")
print(result_mult_ABC5)

A5 + B5:
[[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]
B5 - A5:
[[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]
A5 * C5:
[[ -6  12]
 [  1  45]
 [-17 -19]]
A5 * B5 * C5:
[[ 22 138]
 [-93 129]
 [ 16  56]]
